### ISSUE TITLE
Plugin is building framework only for arm64 and X64

### ISSUE THREAD

**Issue by TomWayne98** [prof18/kmp-fatframework-cocoa#1]
Hello, 

I am trying to provide Cocoapod repository for our iOS team. I expected that the plugin will built the pod for all the architectures (x64, armv7, armv7s and arm64).

However, when we check the supported architectures via this command:` lipo -info [nameOfFramework]` it shows this message:

`Architectures in the fat file: [nameOfFramework] are: x86_64 arm64`

Did I miss some way how to config the plugin? My goal is to be able to deliver framework which run on all iPhone devices and simulator. 

Thank you.

**Comment by prof18** [comment]
Hi,

the plugin automatically detects all the defined source sets. But, if you are using the `ios` target shortcut, [only 64-bit arch are used](https://kotlinlang.org/docs/mpp-share-on-platforms.html#use-target-shortcuts).

To build also 32-bit arch, you need to manually define the sourcsets:

```
kotlin {
    android()

    iosArm32 {
        binaries.framework("LibraryName")
    }
    iosArm64 {
        binaries.framework("LibraryName")
    }
    iosX64 {
        binaries.framework("LibraryName")
    }

    sourceSets {
        val commonMain by getting
        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }
       
       ...

        val iosArm64Main by getting
        val iosArm64Test by getting
        val iosArm32Main by getting
        val iosArm32Test by getting
        val iosX64Main by getting
        val iosX64Test by getting

    }
}
```

I've tried with the setup and the resulting framework was:

```
Architectures in the fat file: LibraryName.framework/LibraryName are: armv7 x86_64 arm64
```

(And just to avoid duplicating code into different source sets, you can use a symlink)
